# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/guacamoleb/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),guacamoleb)

endif

LOCAL_CHECK_ELF_FILES := false
LOCAL_ALLOW_UNDEFINED_SYMBOLS := true
